# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import log_functions_pb2 as log__functions__pb2


class Invoke_FunctionsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.check_message_presence = channel.unary_unary(
                '/log_functions.Invoke_Functions/check_message_presence',
                request_serializer=log__functions__pb2.TimeStampRequest.SerializeToString,
                response_deserializer=log__functions__pb2.TimeStampPresence.FromString,
                )
        self.get_matched_logs = channel.unary_unary(
                '/log_functions.Invoke_Functions/get_matched_logs',
                request_serializer=log__functions__pb2.TimeStampRequest.SerializeToString,
                response_deserializer=log__functions__pb2.MatchedLogs.FromString,
                )


class Invoke_FunctionsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def check_message_presence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_matched_logs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Invoke_FunctionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'check_message_presence': grpc.unary_unary_rpc_method_handler(
                    servicer.check_message_presence,
                    request_deserializer=log__functions__pb2.TimeStampRequest.FromString,
                    response_serializer=log__functions__pb2.TimeStampPresence.SerializeToString,
            ),
            'get_matched_logs': grpc.unary_unary_rpc_method_handler(
                    servicer.get_matched_logs,
                    request_deserializer=log__functions__pb2.TimeStampRequest.FromString,
                    response_serializer=log__functions__pb2.MatchedLogs.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'log_functions.Invoke_Functions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Invoke_Functions(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def check_message_presence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log_functions.Invoke_Functions/check_message_presence',
            log__functions__pb2.TimeStampRequest.SerializeToString,
            log__functions__pb2.TimeStampPresence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_matched_logs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/log_functions.Invoke_Functions/get_matched_logs',
            log__functions__pb2.TimeStampRequest.SerializeToString,
            log__functions__pb2.MatchedLogs.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
