# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: log_functions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13log_functions.proto\x12\rlog_functions\"P\n\x10TimeStampRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\n\n\x02\x64T\x18\x02 \x01(\t\x12\x0f\n\x07logFile\x18\x03 \x01(\t\x12\x0c\n\x04getX\x18\x04 \x01(\t\"8\n\x11TimeStampPresence\x12\x0f\n\x07message\x18\x01 \x01(\x08\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\"/\n\x0bMatchedLogs\x12\x0c\n\x04logs\x18\x01 \x03(\t\x12\x12\n\nstatusCode\x18\x02 \x01(\x05\x32\xc4\x01\n\x10Invoke_Functions\x12]\n\x16\x63heck_message_presence\x12\x1f.log_functions.TimeStampRequest\x1a .log_functions.TimeStampPresence\"\x00\x12Q\n\x10get_matched_logs\x12\x1f.log_functions.TimeStampRequest\x1a\x1a.log_functions.MatchedLogs\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'log_functions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMESTAMPREQUEST._serialized_start=38
  _TIMESTAMPREQUEST._serialized_end=118
  _TIMESTAMPPRESENCE._serialized_start=120
  _TIMESTAMPPRESENCE._serialized_end=176
  _MATCHEDLOGS._serialized_start=178
  _MATCHEDLOGS._serialized_end=225
  _INVOKE_FUNCTIONS._serialized_start=228
  _INVOKE_FUNCTIONS._serialized_end=424
# @@protoc_insertion_point(module_scope)
